language: node_js
sudo: false
before_install:
  - npm install eslint-plugin-import@^1.16.0 jasmine parse parse-server
node_js:
  - "4"
  - "5"
  - "6"

after_success:
  - bash <(curl -s https://codecov.io/bash)
